### enrich assigment

http://localhost:5000/actito-promo-demo/us-central1/enrichAssignment
Content-Type: application/json

{
  "id":26,
  "tableType":"CUSTOM_TABLE",
  "tableId":"bcae0862-281b-4c8f-a0cb-c7535ef8de11",
  "fields":null,
  "eventType":"CREATE",
  "data":{
    "id":"26",
    "synchronized":"false", 
    "profileReference": "alaindresse@gmail.com",
    "offerReference":"springoffer"
  }
}

### get shopify customer

POST http://localhost:5000/actito-promo-demo/us-central1/allowCustomerDiscount
Content-Type: application/json

{
  "email":"emilie.piret@actito.com",
  "code":"SPRINGSALE"
}